import { NgClass, NgFor, NgIf, NgStyle } from '@angular/common';
import { Component, EventEmitter, Input, OnChanges, OnInit, Output, SimpleChanges } from '@angular/core';
import { InputNumericComponent, PriorityField } from "../../../components/input-numeric/input-numeric.component";
import { ErrorStepHandling } from '../../../../utils/types/app';
import { resetWarning, selectionStorage, setWarning } from '../../../../utils/redux/selection';
import { prioritySchemaMap } from '../../../fetch.config';

@Component({
  selector: 'app-step-priorities',
  imports: [NgFor, NgStyle, InputNumericComponent, NgClass],
  templateUrl: './step-priorities.component.html',
  styleUrls: ['./step-priorities.component.css', '../step-window/step-window.component.css', '../../../components/styles/button.css']
})

export class StepPrioritiesComponent implements OnChanges, ErrorStepHandling {

  findError(): void {
    let noJumps: boolean = true
    const prCol: any = Array.from(this.stateColumns).filter((val) => val.selected).sort((a: any, b: any): any => a.priority - b.priority)
    for (let index = 0, val = 1; index < prCol.length; index++, val++) {
      // console.log(prCol[index], val)
      if (prCol[index].priority != val) {
        noJumps = false
        break
      }
    }
    // console.log(noJumps)
    // console.log(noJumps)
    if (noJumps && prCol.length) {
      selectionStorage.dispatch(resetWarning(this.index))
    }
    else {
      selectionStorage.dispatch(setWarning([this.index, `Прежде чем перейти дальше, приоритеты у выбранных столбцов должны стоять в порядке возрастания, все от 1 до n - количества выбранных параметров}`]))
    }
    this.onChanged.emit(prCol)
  }
  @Input()
  index!: number
  @Input()
  alias!: Map<string, string>
  @Input()
  ruComponentType!: string
  @Input()
  columns!: string[]
  stateColumns: any[] = []
  prevStateColumns: any[] = []

  autoGeneratedSchema!: boolean
  warningColumns!: number[]
  popupHint!: boolean
  max: number = 0
  @Output()
  public onChanged = new EventEmitter<{
    name: string,
    disabled: boolean,
    warning: boolean,
    selected: boolean,
    priority: number
  }[]>()
  ngOnChanges(changes: SimpleChanges): void {
    this.stateColumns = this.columns.map((col, index) => {
      return {
        name: col,
        disabled: false,
        warning: false,
        selected: false,
        priority: 0
      }
    })
    this.prevStateColumns = Array.from(this.stateColumns)
    this.findError()
    this.onChanged.emit(this.stateColumns)
  }

  onPriorityChanged(obj: any, index: number): void {
    this.stateColumns[index].priority = obj.value
    this.prevStateColumns = this.stateColumns
    this.findError()
  }

  onAutoGeneratedSchemaSelected(): void {
    this.autoGeneratedSchema = !this.autoGeneratedSchema
    if (this.autoGeneratedSchema) {
      this.stateColumns = this.columns.map((col, index) => {
        return {
          name: col,
          disabled: false,
          warning: false,
          selected: true,
          priority: index + 1
        }
      })
      this.stateColumns = []
      const columns: string[] = prioritySchemaMap.get(this.ruComponentType)!
      let length = 0
      for (let i = 0; i < this.columns.length; i++) {
        let exist = false
        let priority = 0
        let selected = false
        for (let j = 0; j < columns.length; j++) {
          if (this.columns[i] === columns[j]) {
            exist = true
            break
          }
        }
        if (exist) {
          length++
          priority = length
          selected = true
        }
        this.stateColumns.push(
          {
            name: this.columns[i],
            disabled: false,
            warning: false,
            selected: selected,
            priority: priority
          }
        )
      }
      this.max = length
    }
    else {
      this.stateColumns = this.prevStateColumns
      this.max = this.stateColumns.filter((val) => val.selected).length
    }
    this.findError()
  }

  selectColumn(column: any, index: number): void {
    this.stateColumns[index].selected = !column.selected
    this.prevStateColumns = this.stateColumns
    this.max = this.stateColumns.filter((val) => val.selected).length
    this.findError()
  }

  stylize(index: number): any {
    const prev = index - 1
    const next = index + 1
    const sides = ["0", "0", "0", "0"]
    if (!this.stateColumns[index].selected) {
      return
    }

    if (prev < 0 || !this.stateColumns[prev].selected) {
      sides[0] = ".25vw"
      sides[1] = ".25vw"
    }

    if (next >= this.stateColumns.length || !this.stateColumns[next].selected) {
      sides[2] = ".25vw"
      sides[3] = ".25vw"
    }
    const str = sides.join()
    return str.replaceAll(",", " ")
  }
}
