import { NgFor, NgStyle } from '@angular/common';
import { Component, EventEmitter, Input, OnChanges, Output, SimpleChanges } from '@angular/core';
import { InputNumericComponent, PriorityField } from "../../../components/input-numeric/input-numeric.component";

@Component({
  selector: 'app-step-priorities',
  imports: [NgFor, InputNumericComponent, NgStyle],
  templateUrl: './step-priorities.component.html',
  styleUrls: ['./step-priorities.component.css', '../step-window/step-window.component.css', '../../../components/styles/button.css']
})

export class StepPrioritiesComponent implements OnChanges {

  @Input()
  index!: number
  @Input()
  allias!: Map<string, string>
  @Input()
  columns!: string[]

  
  autoGeneratedSchema!: boolean
  warningColumns!: number[]
  popupHint!: boolean

  @Output()
  public onChanged = new EventEmitter<Object>()
  obj: any = {}

  ngOnChanges(changes: SimpleChanges): void {
    this.autoGeneratedSchema = false
    this.initPriorities()
    this.onChanged.emit(this.obj)
  }

  onPriorityChanged(obj: PriorityField): void {
    this.obj[obj.label].priority = obj.value
    this.onChanged.emit(this.obj)
  }

  onAutoGeneratedSchemaSelected(): void {
    this.autoGeneratedSchema = !this.autoGeneratedSchema
    this.autoGeneratedSchema ? this.autoGeneratedPriorities() : this.initPriorities()
    this.onChanged.emit(this.obj)
  }



  initPriorities(): void {
    this.obj = {}
    for (const column of this.columns) {
      this.obj[`${column}`] = {
        disabled: false,
        warning: false,
        priority: 0
      }
    }
  }

  autoGeneratedPriorities(): void {
    this.obj = {}
    let index = 0
    for (const column of this.columns) {
      this.obj[`${column}`] = {
        disabled: true,
        warning: false,
        priority: ++index
      }
    }
  }
}
