import { Component, OnInit } from '@angular/core';
import { NavigatorComponent } from "../../components/navigator/navigator.component";
import { NgClass, NgFor, NgIf, NgStyle } from '@angular/common';
import { DropboxProviderComponent } from "../../components/dropbox-provider/dropbox-provider.component";
import { ApiService1 } from '../../../services/api.services1';
import { HttpClientModule } from '@angular/common/http';
import { AppEnum, ComponentTypeRuEnum } from '../../../utils/enum/app.enum';
import { forkJoin } from 'rxjs';
import { prioritySchemaMap, prioritySchemaWrapperMap, props, propsMap } from '../../../assets/fetch.config';
import { ThisReceiver } from '@angular/compiler';
import { Router } from '@angular/router';
import { LoaderComponent } from "../../components/loader/loader.component";
import { DomSanitizer } from '@angular/platform-browser';

interface IStepper {
  step: number,
  obj: any,
  description: string,
  index: number
}

@Component({
  selector: 'app-table-builder',
  imports: [NavigatorComponent, NgStyle, HttpClientModule, NgClass, DropboxProviderComponent, NgFor, LoaderComponent, NgIf],
  providers: [ApiService1],
  templateUrl: './table-builder.component.html',
  styleUrls: ['./table-builder.component.css', '../../components/styles/button.css']
})


export class TableBuilderComponent implements OnInit {
  step!: 0 | -1 | -2
  stepper!: Map<string, Partial<IStepper>>
  currentDropBoxName: string | undefined
  allias!: Map<string, string>
  dropBoxPropsMapConfig!: Map<string, any>
  storage: any
  all: any
  tableColumns!: Map<string, Map<string, string>>
  displayedColumns!: string[]
  selectedColumns!: string[]
  displayedRuComponentTypes!: string[]
  loader!: boolean
  popupHint!: boolean

  constructor(
    private api: ApiService1,
    private router: Router,
    private sanitizer: DomSanitizer
  ) { }

  ngOnInit(): void {
    this.popupHint = false
    this.autoGeneratedSchema = false
    this.all = []
    this.displayedColumns = []
    this.selectedColumns = []
    this.displayedRuComponentTypes = []
    this.storage = new Map()
    this.stepper = new Map()
    this.allias = new Map()
    this.tableColumns = new Map()
    this.step = 0
    this.move()
    const dropBoxPropsClone: any = {};
    for (const [key, value] of Object.entries(props)) {
      dropBoxPropsClone[key] = { ...value };
    }
    this.dropBoxPropsMapConfig = new Map(Object.entries(dropBoxPropsClone));
    this.loader = true
    this.getApi()
  }

  lastSavedSessionExists(): boolean {
    return JSON.parse(window.localStorage.getItem('selection') as string) !== null
  }

  getLastSavedUrl(): any {
    let obj = JSON.parse(window.localStorage.getItem('selection') as string)
    if (obj && Object.keys(obj).length == 2 && obj.tableUrl) {
      // this.router.navigateByUrl(obj.tableUrl)
      return this.sanitizer.bypassSecurityTrustResourceUrl(obj.tableUrl)
    }
    return undefined
  }

  autoGeneratedSchema!: boolean
  onAutoGeneratedSchemaSelected(): void {
    this.autoGeneratedSchema = !this.autoGeneratedSchema
    if (this.autoGeneratedSchema) {
      const table = prioritySchemaWrapperMap.get(this.stepper.get('step1')!.obj)
      this.selectedColumns = prioritySchemaMap.get(table as string) as []
      this.stepper.get('step2')!.obj = this.selectedColumns.length === 0 ? undefined : this.selectedColumns
    }
    else {
      this.selectedColumns = []
      this.stepper.get('step2')!.obj = undefined
    }
  }

  move(): void {
    for (let index = this.step, i = 1; index < this.step + 3; index++, i++) {
      let obj: any = this.stepper.get(`step${i}`)?.obj;
      let description: any = this.stepper.get(`step${i}`)?.description
      this.stepper.set(`step${i}`, {
        step: index * 100,
        obj: obj,
        index: index,
        description: description
      })
    }
  }
  next(): void {
    let obj: any = this.stepper.get(`step${Math.abs(this.step) + 1}`)?.obj;
    if (!obj) {
      alert("Заполните или выберите параметр")
      return
    }
    if (this.step > -2) {
      this.step--
      this.move()
    }
    else {
      this.makeQueryStr()
    }
  }

  makeQueryStr(): void {
    let str = "?"
    for (const column of this.selectedColumns) {
      if (this.dropBoxPropsMapConfig.get(column) || column === 'ruComponentType') {
        console.log(this.dropBoxPropsMapConfig.get(column).currentValue)
        str += `${column}=${this.dropBoxPropsMapConfig.get(column).currentValue}&`
      }
    }
    str += `${'ruComponentType'}=${this.dropBoxPropsMapConfig.get('ruComponentType').currentValue}&`

    str = str.replace('+', '%2B0')
    this.resetStorage()
    this.router.navigateByUrl(`/table-view${str}`)
  }
  prev(): void {
    if (this.step < 0) {
      this.step++
      this.move()
      if (this.step == 0) {
        this.selectedColumns = []
        this.stepper.get('step2')!.obj = undefined
        this.autoGeneratedSchema = false
      }
    }
  }


  onCurrentDropBoxNameChnaged(obj: { propsMap: Map<string, any>, currentName: string | undefined }): void {
    this.currentDropBoxName = obj.currentName
    this.dropBoxPropsMapConfig = obj.propsMap
    let object = Object.fromEntries(this.dropBoxPropsMapConfig)
    for (const key in object) {
      let val = object[key].currentValue
      if (!this.selectedColumnsContains(key)) {
        if (!val.trim() || val == AppEnum.ALL) {
          this.stepper.get('step3')!.obj = undefined
          return
        }
      }
    }
    this.stepper.get('step3')!.obj = this.dropBoxPropsMapConfig
  }
  getApi(): void {
    forkJoin([
      this.api.getDiods(),
      this.api.getTransistors(),
      this.api.getCapacitors(),
      this.api.getMicrochips(),
      this.api.getResistors(),
      this.api.getAlias()
    ])
      .subscribe(res => {
        this.storage.set(ComponentTypeRuEnum.DIOD, (res as any[])[0])
        this.storage.set(ComponentTypeRuEnum.TRANSISTOR, (res as any[])[1])
        this.storage.set(ComponentTypeRuEnum.CAPACITOR, (res as any[])[2])
        this.storage.set(ComponentTypeRuEnum.MICROCHIP, (res as any[])[3])
        this.storage.set(ComponentTypeRuEnum.RESISTOR, (res as any[])[4])
        const allias = (res as any[])[5]
        this.allias = new Map<string, string>(Object.entries(allias))
        if (this.storage.size === 5) {
          this.storage.forEach((set: any) => {
            (set as []).forEach((item: any) => {
              this.all.push({
                component: item
              })
              if (!this.tableColumns.get(item.ruComponentType)) {
                const tmp = new Map()
                for (const key in item) {
                  const componentProps = this.dropBoxPropsMapConfig.get(key)
                  const alliasName = this.allias.get(`${key}`)
                  if (alliasName && componentProps && key !== 'ruComponentType') {
                    tmp.set(key, alliasName)
                  }
                }
                this.tableColumns.set(item.ruComponentType, tmp)
              }
            })
          })
          this.displayedRuComponentTypes = Array.from(this.tableColumns.keys())
          this.loader = false
        }
      });
  }

  selectedColumnsContains(column: string): boolean {
    return this.selectedColumns.find((value) => value == column) === undefined
  }

  onTypeSelected(ruComponentType: string): void {
    let value: string = AppEnum.ALL
    let displayedColumns: string[] = []
    this.stepper.get('step1')!.obj = null
    if (this.dropBoxPropsMapConfig.get('ruComponentType').currentValue !== ruComponentType) {
      value = ruComponentType
      displayedColumns = Array.from(this.tableColumns.get(`${ruComponentType}`)!.keys())
      this.stepper.get('step1')!.obj = value
    }
    this.displayedColumns = displayedColumns
    this.dropBoxPropsMapConfig.get('ruComponentType').currentValue = value
    // console.log(this.dropBoxPropsMapConfig.get('ruComponentType').currentValue)
    // console.log(this.displayedColumns)
  }

  onColumnSelected(column: string): void {
    if (this.selectedColumnsContains(column)) {
      this.selectedColumns.push(column)
    }
    else {
      this.selectedColumns = this.selectedColumns.filter((value) => value !== column)
    }
    this.stepper.get('step2')!.obj = this.selectedColumns.length === 0 ? undefined : this.selectedColumns
  }
  displayedRuComponentTypeHeader(): string {
    let value = this.dropBoxPropsMapConfig.get('ruComponentType').currentValue
    return value === AppEnum.ALL ? "" : value
  }
  resetStorage(): void {
    window.localStorage.removeItem('selection')
  }
}
