import { Component, EventEmitter, Input, OnInit, Output } from '@angular/core';
import { SelectListCheckboxComponent } from "../../components/select-list-checkbox/select-list-checkbox.component";
import { ListCheckboxComponent } from "../../components/list-checkbox/list-checkbox.component";
import { chartNamesMap } from '../../../utils/static-data/chart-names';
import { NgFor, NgIf, NgStyle } from '@angular/common';
import { HttpClientModule } from '@angular/common/http';
import { ApiService } from '../../../services/api.services';
import { ChartTemplateComponent } from "../../components/charts/chart-template.component";
import { ChartBodyRequest, ComponentTypes } from '../../../utils/types/app';
import { AppEnum } from '../../../utils/enum/app.enum';
import { LoaderComponent } from "../../components/loader/loader.component";

@Component({
  selector: 'app-report-builder',
  imports: [NgFor, ChartTemplateComponent, LoaderComponent, NgIf],
  providers: [HttpClientModule, ApiService],
  templateUrl: './report-builder.component.html',
  styleUrls: ['./report-builder.component.css', '../../components/styles/button.css']
})
export class ReportBuilderComponent implements OnInit {
  loader!: boolean
  @Input()
  autoGeneratedSchema!: boolean
  onBlobLoaded(chart: [string, string]) {
    let index = this.prioritiesChartsEntries.findIndex((val) => val[0] === chart[1])
    if (index != -1) {
      this.prioritiesChartsEntries[index][1]['mainChartQuery'].set('image', chart[0])
    }
    this.loader = false
  }

  constructor(
    private api: ApiService
  ) { }
  ngOnInit(): void {
    this.loader = true
  }
  getChartNameAlias(typeName: string): string {
    return chartNamesMap.get(typeName)!
  }

  @Input()
  prioritiesChartsEntries!: any[]
  base64ToBlob(base64: string): Promise<Blob> {
    return fetch(base64).then(res => res.blob());
  }
  generate(): void {
    const reports: ChartBodyRequest[] = [];
    const formData = new FormData();
    const promises: Promise<any>[] = []
    // // console.log(this.prioritiesChartsEntries)
    this.loader = true;
    this.prioritiesChartsEntries.forEach((priority, index) => {
      const base64 = priority[1]['mainChartQuery'].get('image');

      // console.log(priority)
      const promise = this.base64ToBlob(base64).then((blob: any) => {
        formData.append('files', blob, `chart_${index}.png`);
      });
      promises.push(promise)
      const fileName = `chart_${index}.png`;
      reports.push({
        ChartLabel: priority[1]['chartLabel'],
        ParameterName: priority[1]['mainChartQuery'].get('priority')[0],
        ParameterValue: priority[1]['mainChartQuery'].get('priority')[1] == AppEnum.NOTDEFINED ? 'null' : priority[1]['mainChartQuery'].get('priority')[1],
        Image: fileName,
        TypeName: priority[1]['typeName']
      });
    })
    Promise.all(promises).then((blob) => {
      formData.append('reports', JSON.stringify(reports));
      formData.append('autoGeneratedSchema', JSON.stringify(this.autoGeneratedSchema));
      this.api.makeReport(formData, this.currentComponentType.enComponentType).subscribe((blob: Blob) => {
        this.loader = false
        const url = window.URL.createObjectURL(blob);
        const link = document.createElement('a');
        link.href = url;
        const currentDate: Date = new Date()
        link.download = `report-${currentDate.getDate()}-${currentDate.getMonth()}-${currentDate.getFullYear()}.pdf`;
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
        window.URL.revokeObjectURL(url);
        this.close()
      })
    })
    .catch(() => this.loader = false)

  }
  @Output()
  public onClose = new EventEmitter<void>()
  @Input()
  alias: Map<string, string> = new Map()
  @Input()
  currentComponentType!: ComponentTypes
  close(): void {
    this.onClose.emit()
  }
}
